config/routes.rb
Rails.application.routes.draw do
  resources :head_phones
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/head_phone.rb
class HeadPhone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/head_phones_controller.rb
class HeadPhonesController < ApplicationController
  before_action :set_head_phone, only: [:show, :edit, :update, :destroy]

  # GET /head_phones
  # GET /head_phones.json
  def index
    @head_phones = HeadPhone.all
  end

  # GET /head_phones/1
  # GET /head_phones/1.json
  def show
  end

  # GET /head_phones/new
  def new
    @head_phone = HeadPhone.new
  end

  # GET /head_phones/1/edit
  def edit
  end

  # POST /head_phones
  # POST /head_phones.json
  def create
    @head_phone = HeadPhone.new(head_phone_params)

    respond_to do |format|
      if @head_phone.save
        format.html { redirect_to @head_phone, notice: 'Head phone was successfully created.' }
        format.json { render :show, status: :created, location: @head_phone }
      else
        format.html { render :new }
        format.json { render json: @head_phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /head_phones/1
  # PATCH/PUT /head_phones/1.json
  def update
    respond_to do |format|
      if @head_phone.update(head_phone_params)
        format.html { redirect_to @head_phone, notice: 'Head phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @head_phone }
      else
        format.html { render :edit }
        format.json { render json: @head_phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /head_phones/1
  # DELETE /head_phones/1.json
  def destroy
    @head_phone.destroy
    respond_to do |format|
      format.html { redirect_to head_phones_url, notice: 'Head phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_head_phone
      @head_phone = HeadPhone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def head_phone_params
      params.require(:head_phone).permit(:name, :tendency, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/head_phones_helper.rb
module HeadPhonesHelper
end

app/views/head_phones/_form.html.erb
<%= form_with(model: head_phone, local: true) do |form| %>
  <% if head_phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(head_phone.errors.count, "error") %> prohibited this head_phone from being saved:</h2>

      <ul>
      <% head_phone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :tendency %>
    <%= form.text_field :tendency %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/head_phones/edit.html.erb
<h1>Editing Head Phone</h1>

<%= render 'form', head_phone: @head_phone %>

<%= link_to 'Show', @head_phone %> |
<%= link_to 'Back', head_phones_path %>

app/views/head_phones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Head Phones</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tendency</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @head_phones.each do |head_phone| %>
      <tr>
        <td><%= head_phone.name %></td>
        <td><%= head_phone.tendency %></td>
        <td><%= head_phone.price %></td>
        <td><%= link_to 'Show', head_phone %></td>
        <td><%= link_to 'Edit', edit_head_phone_path(head_phone) %></td>
        <td><%= link_to 'Destroy', head_phone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Head Phone', new_head_phone_path %>

app/views/head_phones/new.html.erb
<h1>New Head Phone</h1>

<%= render 'form', head_phone: @head_phone %>

<%= link_to 'Back', head_phones_path %>

app/views/head_phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @head_phone.name %>
</p>

<p>
  <strong>Tendency:</strong>
  <%= @head_phone.tendency %>
</p>

<p>
  <strong>Price:</strong>
  <%= @head_phone.price %>
</p>

<%= link_to 'Edit', edit_head_phone_path(@head_phone) %> |
<%= link_to 'Back', head_phones_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SerendipityPhoneRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>